../../vendor/lowrisc_ip/ip/prim/rtl/prim_count.sv
../../vendor/lowrisc_ip/ip/prim_generic/rtl/prim_generic_and2.sv
../../dv/uvm/core_ibex/common/prim/prim_and2.sv
../../vendor/lowrisc_ip/ip/prim_generic/rtl/prim_generic_clock_mux2.sv
../../dv/uvm/core_ibex/common/prim/prim_clock_mux2.sv
../../vendor/lowrisc_ip/ip/prim_generic/rtl/prim_generic_flop.sv
../../vendor/lowrisc_ip/ip/prim/rtl/prim_ram_1p_pkg.sv
../../vendor/lowrisc_ip/ip/prim/rtl/prim_secded_inv_39_32_enc.sv
../../vendor/lowrisc_ip/ip/prim/rtl/prim_secded_inv_39_32_dec.sv
../../vendor/lowrisc_ip/ip/prim/rtl/prim_secded_pkg.sv
../../vendor/lowrisc_ip/ip/prim_generic/rtl/prim_generic_buf.sv
../../vendor/lowrisc_ip/ip/prim/rtl/prim_cipher_pkg.sv
../../vendor/lowrisc_ip/ip/prim/rtl/prim_lfsr.sv
../../vendor/lowrisc_ip/ip/prim/rtl/prim_onehot_check.sv
../../vendor/lowrisc_ip/ip/prim/rtl/prim_onehot_enc.sv
../../vendor/lowrisc_ip/ip/prim/rtl/prim_onehot_mux.sv
../../syn/rtl/prim_clock_gating.v
../../dv/uvm/core_ibex/common/prim/prim_buf.sv
../../dv/uvm/core_ibex/common/prim/prim_flop.sv
../../rtl/ibex_pkg.sv
../../rtl/ibex_register_file_ff.sv
../../rtl/ibex_alu.sv
../../rtl/ibex_branch_predict.sv
../../rtl/ibex_compressed_decoder.sv
../../rtl/ibex_controller.sv
../../rtl/ibex_cs_registers.sv
../../rtl/ibex_csr.sv
../../rtl/ibex_counter.sv
../../rtl/ibex_decoder.sv
../../rtl/ibex_ex_block.sv
../../rtl/ibex_fetch_fifo.sv
../../rtl/ibex_id_stage.sv
../../rtl/ibex_if_stage.sv
../../rtl/ibex_load_store_unit.sv
../../rtl/ibex_multdiv_fast.sv
../../rtl/ibex_multdiv_slow.sv
../../rtl/ibex_prefetch_buffer.sv
../../rtl/ibex_pmp.sv
../../rtl/ibex_wb_stage.sv
../../rtl/ibex_dummy_instr.sv
../../rtl/ibex_core.sv
../../rtl/ibex_lockstep.sv
../../rtl/ibex_top.sv
../../dv/bug_cf_hijack_load_branch/tb_top.sv